title: practicerx
email: your-email@domain.com
description: navigating your transition to clinical practice
baseurl: ""
url: "https://practicerx.github.io"
twitter_username: practice_rx
github_username:  practicerx

# Build settings
markdown: kramdown
# theme: minima
permalink: /:year/:month–:day–:title/

# Gemfile, Gemfile.lock - The Gemfile and Gemfile.lock files are used by Bundler to keep track of the required gems and gem versions you need to build your Jekyll site.

sass:
  sass_dir:  _sass
  style:  compressed

gems:
  - jekyll-feed
  - jekyll-github-metadata
#  - jekyll-admin
  - jekyll-paginate
#  - jekyll-compose
#  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-livereload
#  - jekyll-assets
#  - autoprefixer-rails
#  - bourbon
#  - neat

exclude:
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - google*.html
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - scss
  - _sass
  - css
  - media
  - ".bundle"
  - vendor
  - node_modules
  - assets/podcast
